---
name: 'Studio Release GitHub Action'
description: |
  GitHub Action for creating a repository release using RTK.
author: 'Cliffano Subagio'
branding:
  icon: 'bookmark'
  color: 'black'
inputs:
  release_type:
    description: RTK release type, options are 'major', 'minor', 'patch'
    type: string
    required: false
    default: 'minor'
  github_token:
    description: GitHub token
    type: string
    required: true
  git_user_name:
    description: Git user name
    type: string
    required: false
    default: pakkunbot
  git_user_email:
    description: Git user email
    type: string
    required: false
    default: blah+pakkun@cliffano.com
runs:
  using: 'composite'
  steps:
    - name: Checkout code from the current repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        set-safe-directory: ${{ github.workspace }}
    - name: Setup node.js, needed to run RTK
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Set @pakkunbot's email as git user email
      shell: bash
      run: git config --global user.email "${{ inputs.git_user_email }}"
    - name: Set @pakkunbot's username as git user name
      shell: bash
      run: git config --global user.name "${{ inputs.git_user_name }}"
    - name: Install RTK
      shell: bash
      run: npm install -g rtk
    - name: Cut off a release
      shell: bash
      run: rtk release --release-increment-type ${{ inputs.release_type }}
    - name: Push the changes to remote repository
      uses: ad-m/github-push-action@v0.8.0
      with:
        tags: true
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
